# Generated by Django 4.2.6 on 2023-11-08 06:00

from django.db import migrations, models
import main.utils.file_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_courses_studentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='otp',
            field=models.CharField(default='123456', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ImageField(default='default-images\\Ellipse_2.png', upload_to=main.utils.file_helpers.custom_file_name),
        ),
    ]
