# Generated by Django 4.2.6 on 2024-01-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_employee_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.ImageField(default='default_images\\Ellipse_2.png', upload_to='employees'),
        ),
    ]
